### ISSUE TITLE
Very long loading time with no indicator

### ISSUE THREAD

**Issue by MidnightDriveApps** [BSFEMA/linux_file_rename_utility#2]
Small issue in terms of usage, maybe large as for a fix (or maybe not?), but when a directory is selected (from the top-left dropdown within the GUI) with a particularly large amount of files/folders/subfolders, the GUI simply freezes with no indicator  that anything is happening. 

Once it's known then it's not a showstopper to using the utility to be sure, but may be off-putting to new users, and in general would be a nice touch to have a spinner going or something for assurance that processing is occurring.

For context this has happened for me mostly with CIFS mounted network drives with nearly 1000 folders and over 5000 files within them, so this may be only an issue in such extreme cases

**Comment by BSFEMA** [comment]
This should be fixed in v1.10.

The cursor will now change to a waiting icon when the data grid is loading.
